spring:
   config:
    activate:
      on-profile: Development
   datasource:
    url: ${url}
    username: ${username}
    password: ${password}
   jpa:    hibernate:      ddl-auto: update

---

spring:
   config:    activate:      on-profile: Staging
   datasource:    url: ${url}
    username: ${username}
    password: ${password} 
   jpa:    hibernate:      ddl-auto: update